container:
  image: node:12

lint_task:
  install_script: npm install
  test_script: npm run lint

test_task:
  container:
    matrix:
      image: node:14
      image: node:12
      image: node:10
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[fd716b8f8f9b64712c6998612b21c0394a986b81c4fbdd82b48de183b92250b6d09c1ed047b42e4f92b9a6e61281d05d]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - test
    - lint
  environment:
    GITHUB_TOKEN: ENCRYPTED[2b11114754553f769266cb5f80b922c1e4be66fd4c25008c1810e1b95714de03461cb5359df782b7c15335e3c2054be1]
    NPM_TOKEN: ENCRYPTED[d6b69af024cc8db7b00e916f18cc0402747d7deb00b7bc96890b8dfef4d9a9fef4a778f2272e6fbf2cce673a1c5e5eee]
  script:
    - npm install
    - npx semantic-release
